name: Mirror to GitVerse & SourceCraft

on:
  push:
    branches: [ main, master ]
    tags: [ '*' ]
  release:
    types: [published, edited]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Важно! Полная история
        fetch-tags: true
    
    - name: Push to GitVerse
      run: |
        git remote add gitverse https://${{ secrets.GITVERSE_TOKEN }}@gitverse.ru/aabogatkina/study_2026-2027_simulation-networks.git
        git push gitverse --all
        git push gitverse --tags
    
    - name: Push to SourceCraft
      run: |
        git remote add sourcecraft https://${{ secrets.SOURCECRAFT_USERNAME }}:${{ secrets.SOURCECRAFT_TOKEN }}@git.sourcecraft.dev/aabogatkina/study-2026-2027-simulation-networks.git
        git push sourcecraft --all
        git push sourcecraft --tags
